### ISSUE TITLE
Modos de debug

### ISSUE THREAD

**Issue by 20leunam** [OPRobots/FujitoraBot#1]
Al seleccionar cada uno de los siguientes modos de debug el led RGB se iluminará con el color correspondiente al modo. Al igual que el menú de velocidad y succión.
- Sensores Raw (cian)
- Sensores calibrados (verde suave)
- Posición de linea (verde)
- Debug motores (amarillo suave)
- Encoders (amarillo)
- Entradas digitales (rojo suave)
- ... (rojo)
- ... (morado suave)
- Fiesta de leds (morado)
- Demostración succión (ultra-instinto)

**Cuando se selecciona un modo de debug se arranca y para con el boton "Start" y fadeará el color correspondiente mientras esté activado. (excepto en "Fiesta de leds" creo)

**Comment by 20leunam** [comment]
En el tema de analizar si los encoders fallan sería interesante utilizar el index y el numero de pulsos por vuelta para determinar si están dando problemas o no. 
En caso de detectar irregularidad en los pulsos de los encoders entre paso y paso del index quizas se podria poner en "alarma" el robot para notificarnoslo, y que pasase automaticamente a de m/s a pwm

**Comment by robotaleh** [comment]
> En el tema de analizar si los encoders fallan sería interesante utilizar el index y el numero de pulsos por vuelta para determinar si están dando problemas o no.
> En caso de detectar irregularidad en los pulsos de los encoders entre paso y paso del index quizas se podria poner en "alarma" el robot para notificarnoslo, y que pasase automaticamente a de m/s a pwm

Esto mejor se pasa a un "pending" a parte.
