### ISSUE TITLE
PID a 1ms

### ISSUE THREAD

**Issue by 20leunam** [OPRobots/FujitoraBot#3]
Cambiar la velocidad de PID a 1ms y que la asignación de velocidad sea inmediatamente despues del calculo del PID, siendo esta, por tanto, asignada también cada 1ms.

**Intentar hacer funcionar los brushless con OneShot 42 (12khz) aunque no coincidan los prescalers

**Comment by robotaleh** [comment]
> **Intentar hacer funcionar los brushless con OneShot 42 (12khz) aunque no coincidan los prescalers

Al jugar con los prescalers se consiguen frecuencias de 11,7kHz o 12,6kHz. Con la primera los ESC no se inician y con la segunda arrancan sin control a máxima velocidad; en un futuro si eso se vuelve a intentar.
