### ISSUE TITLE
Sistema de setup

### ISSUE THREAD

**Issue by 20leunam** [OPRobots/FujitoraBot#4]
Como se deberá comportar el robot en cuanto se encienda:
- Encender robot
- Inicializar timers, relojes, motores, etc.
- Comprobar el estado de los Switches
- Calibrar (en función de los switches calibrará de una u otra forma)
- Atender a los botones de configuración.

**Comment by robotaleh** [comment]
Esto ya está listo al atender las issues #1 y #2
