### ISSUE TITLE
The BIGGER Filtro

### ISSUE THREAD

**Issue by 20leunam** [OPRobots/FujitoraBot#6]
The BIGGER Filtro

Realizar un filtro de marcas en el array principal, de tal forma que solo haga caso a la linea central e ignore los sensores que están alejados de la linea dado que se entiende que la información que aporten es irrelevante.

**Teóricamente con este filtro se deberia autoresolverse la issue de: The BIG Filtro

**Comment by 20leunam** [comment]
Quiero hacer especial hincapié en probar los filtros de manera exhaustiva mediante prints de posición de linea sobre el escritorio, con un folio y cinta aislante, con los motores parados. una vez los prints, el serial ploter y todo diga que funcione, probar en pista. Así se ahorra batería, se aumenta el número de pruebas y se evitan desgracias.

**Comment by robotaleh** [comment]
> The BIGGER Filtro
> 
> **Teóricamente con este filtro se deberia autoresolverse la issue de: The BIG Filtro

Este filtro es totalmente distinto del #5 ya que este filtra las marcas cuando no hay ningún salto. De hecho, en caso de que todos los sensores estén detectando, este filtro lo que haría sería dejar detectando solo los comprendidos entre la línea anterior.
